import React, { useEffect, useMemo, useRef, useState } from 'react';
import { z } from 'zod';
import type { AccentProfileV1, AccentScoreV1, PracticePromptV1 } from 'mockmate-shared';
import { AccentProfileV1Schema, AccentScoreV1Schema, PracticePromptV1Schema } from 'mockmate-shared';
import { apiClient } from '../../services/apiClient';
import { useAudioRecorder } from './useAudioRecorder';

const Catalog = z.object({ contractVersion:z.literal('accent-profile-catalog.v1'), profiles:z.array(AccentProfileV1Schema), practiceModes:z.array(z.string()), fixture:z.literal(true), retention:z.literal('derived-results-only') });
const Prompt = z.object({ prompt:PracticePromptV1Schema, scoringPolicyVersion:z.string(), fixture:z.literal(true) });
const Result = z.object({ score:AccentScoreV1Schema, replayed:z.boolean(), requestHash:z.string(), adapter:z.literal('scoring-unavailable-v1'), retention:z.literal('derived-results-only') });
const Disposition = z.object({ status:z.enum(['pending','cancelled','committed','conflict','missing']), requestHash:z.string().nullish(), result:AccentScoreV1Schema.optional() });
const Authority = z.object({ attemptId:z.string().uuid(), capability:z.string().regex(/^[a-f0-9]{64}$/), expiresAt:z.string() });
const History = z.object({ attempts:z.array(z.object({ attempt_id:z.string(), result:AccentScoreV1Schema, fixture:z.boolean(), evidenceProvenance:z.string(), evidenceStatus:z.record(z.string(),z.string()), duration_ms:z.number(), mime_type:z.string(), created_at:z.string() }).passthrough()).max(50), retention:z.literal('derived-results-only') });
type HistoryAttempt = z.infer<typeof History>['attempts'][number];
const modes = [['word','Word'],['phrase','Phrase'],['sentence_reading','Sentence'],['free_response','Free response']] as const;

export default function AccentPracticeV1({ onExit }:{ onExit:()=>void }) {
 const recorder=useAudioRecorder(); const [profiles,setProfiles]=useState<AccentProfileV1[]>([]); const [profileId,setProfileId]=useState('en-GB-general-v1'); const [mode,setMode]=useState<typeof modes[number][0]>('word'); const [prompt,setPrompt]=useState<PracticePromptV1|null>(null); const [policy,setPolicy]=useState(''); const [score,setScore]=useState<AccentScoreV1|null>(null); const [error,setError]=useState('');
 const previewUrl=useMemo(()=>recorder.audioBlob?URL.createObjectURL(recorder.audioBlob):'',[recorder.audioBlob]); useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
 const promptGeneration=useRef(0); const promptController=useRef<AbortController|null>(null);
 const uploadGeneration=useRef(0); const uploadController=useRef<AbortController|null>(null); const uploadPayload=useRef<FormData|null>(null);
 const pendingSubmit=useRef<Promise<void>|null>(null); const attemptId=useRef<string|null>(null); const submissionCapability=useRef<string|null>(null); const authorityRequest=useRef<Record<string,unknown>|null>(null); const practiceGeneration=useRef(0); const [submitting,setSubmitting]=useState(false);
 const [history,setHistory]=useState<HistoryAttempt[]>([]); const [historyError,setHistoryError]=useState(''); const [historyLoading,setHistoryLoading]=useState(false); const [deletingId,setDeletingId]=useState<string|null>(null); const historyGeneration=useRef(0);
 const loadHistory=async()=>{const generation=++historyGeneration.current;setHistoryLoading(true);setHistoryError('');try{const x=await apiClient.get('clearspeak/v1/accent/attempts',History,{params:{limit:'20'}});if(generation===historyGeneration.current)setHistory(x.attempts)}catch{if(generation===historyGeneration.current)setHistoryError('History is unavailable. Your saved attempts were not changed.')}finally{if(generation===historyGeneration.current)setHistoryLoading(false)}};
 const cancelSubmission=async(updateState=true,applyCompletion=true)=>{const id=attemptId.current;let capability=submissionCapability.current;const request=authorityRequest.current;const generation=practiceGeneration.current;uploadGeneration.current++;uploadController.current?.abort();uploadController.current=null;uploadPayload.current=null;pendingSubmit.current=null;if(updateState)setSubmitting(false);if(applyCompletion&&generation===practiceGeneration.current){recorder.abortRecording();setScore(null);setError('')}if(!id)return 'cancelled' as const;try{if(!capability&&request){const authority=await apiClient.post('clearspeak/v1/accent/attempt-authority',Authority,request);capability=authority.capability;if(attemptId.current===id)submissionCapability.current=capability}if(!capability)return 'cancelled' as const;const outcome=await apiClient.post(`clearspeak/v1/accent/attempts/${encodeURIComponent(id)}/cancel`,Disposition,{submissionCapability:capability});const terminal=['committed','cancelled','conflict','missing'].includes(outcome.status);if(terminal&&attemptId.current===id){attemptId.current=null;submissionCapability.current=null;authorityRequest.current=null}if(!applyCompletion||generation!==practiceGeneration.current)return outcome.status;if(outcome.status==='committed'&&outcome.result){setScore(outcome.result);recorder.clearAudio();void loadHistory()}return outcome.status}catch{if(applyCompletion&&generation===practiceGeneration.current)setError('Cancellation was not confirmed. Check attempt status before recording again.');return 'unknown' as const}};
 useEffect(()=>{const controller=new AbortController();apiClient.get('clearspeak/v1/accent/catalog',Catalog,{signal:controller.signal}).then(x=>setProfiles(x.profiles)).catch(()=>{if(!controller.signal.aborted)setError('Accent practice is unavailable.')});void loadHistory();return()=>{controller.abort();historyGeneration.current++}},[]);
 useEffect(()=>{practiceGeneration.current++;void cancelSubmission(false,false);const controller=new AbortController();promptController.current?.abort();promptController.current=controller;const generation=++promptGeneration.current;setScore(null);setPrompt(null);recorder.abortRecording();apiClient.post('clearspeak/v1/accent/prompts',Prompt,{profileId,profileVersion:1,mode},{signal:controller.signal}).then(x=>{if(controller.signal.aborted||generation!==promptGeneration.current)return;setPrompt(x.prompt);setPolicy(x.scoringPolicyVersion)}).catch(()=>{if(!controller.signal.aborted&&generation===promptGeneration.current)setError('Could not load this prompt.')});return()=>{controller.abort();promptGeneration.current++;practiceGeneration.current++;void cancelSubmission(false,false)}},[profileId,mode]);
 useEffect(()=>()=>{promptController.current?.abort();practiceGeneration.current++;void cancelSubmission(false,false)},[]);
 const submit=()=>{if(pendingSubmit.current)return pendingSubmit.current;if(!navigator.onLine){setError('You are offline. No result was created.');return Promise.resolve()}if(!prompt||!recorder.audioBlob)return Promise.resolve();const generation=++uploadGeneration.current;const practice=practiceGeneration.current;const controller=new AbortController();uploadController.current=controller;attemptId.current??=crypto.randomUUID();authorityRequest.current??={attemptId:attemptId.current,mode,profileId,profileVersion:prompt.profileVersion,promptId:prompt.promptId,promptVersion:prompt.promptVersion,promptContentHash:prompt.contentHash,referenceSetVersion:prompt.referenceSetVersion,scoringPolicyVersion:policy};setSubmitting(true);setError('');const run=(async()=>{if(!submissionCapability.current){const authority=await apiClient.post('clearspeak/v1/accent/attempt-authority',Authority,authorityRequest.current,{signal:controller.signal});submissionCapability.current=authority.capability}const form=new FormData();uploadPayload.current=form;form.append('audio',recorder.audioBlob!,'ephemeral-recording.webm');form.append('metadata',JSON.stringify({attemptId:attemptId.current,submissionCapability:submissionCapability.current,durationMs:recorder.durationMs,mode,profileId,profileVersion:prompt.profileVersion,promptId:prompt.promptId,promptVersion:prompt.promptVersion,promptContentHash:prompt.contentHash,referenceSetVersion:prompt.referenceSetVersion,scoringPolicyVersion:policy}));const x=await apiClient.post('clearspeak/v1/accent/attempts',Result,form,{signal:controller.signal});if(controller.signal.aborted||generation!==uploadGeneration.current||practice!==practiceGeneration.current)return;setScore(x.score);recorder.clearAudio();attemptId.current=null;submissionCapability.current=null;authorityRequest.current=null;void loadHistory()})().catch(()=>{if(controller.signal.aborted||generation!==uploadGeneration.current||practice!==practiceGeneration.current)return;setError('The response was not confirmed. Retry this same recording to recover any committed result.')}).finally(()=>{if(generation!==uploadGeneration.current||practice!==practiceGeneration.current)return;setSubmitting(false);pendingSubmit.current=null;uploadController.current=null;uploadPayload.current=null});pendingSubmit.current=run;return run};
 const deleteAttempt=async(id:string)=>{if(deletingId)return;setDeletingId(id);setHistoryError('');try{await apiClient.deleteVoid(`clearspeak/v1/accent/attempts/${encodeURIComponent(id)}`);setHistory(current=>current.filter(item=>item.attempt_id!==id))}catch{setHistoryError('Delete failed. The attempt remains in your history.')}finally{setDeletingId(null)}};
 const recoverSubmission=async()=>{const id=attemptId.current;const generation=practiceGeneration.current;if(!id)return;try{const outcome=await apiClient.get(`clearspeak/v1/accent/attempts/${encodeURIComponent(id)}/status`,Disposition);if(generation!==practiceGeneration.current||attemptId.current!==id)return;if(outcome.status==='committed'&&outcome.result){setScore(outcome.result);recorder.clearAudio();attemptId.current=null;submissionCapability.current=null;authorityRequest.current=null;setError('');void loadHistory()}else if(outcome.status==='cancelled'||outcome.status==='missing'){recorder.abortRecording();attemptId.current=null;submissionCapability.current=null;authorityRequest.current=null;setError(outcome.status==='cancelled'?'This attempt was authoritatively cancelled.':'This attempt is no longer available.')}else setError(`Attempt status: ${outcome.status}. You may retry the same recording.`)}catch{if(generation===practiceGeneration.current&&attemptId.current===id)setError('Attempt status is temporarily unavailable. Your recording and attempt identity were preserved.')}};
 const cancelPractice=()=>{promptController.current?.abort();return cancelSubmission()};
 return <main className="mx-auto w-full max-w-3xl overflow-x-hidden p-4 text-white sm:p-8" aria-live="polite"><button onClick={()=>{void cancelPractice().then(()=>onExit())}} className="mb-5 text-sm text-brand-tint focus:ring-2">← ClearSpeak home</button><h1 className="text-3xl font-semibold">Accent practice V1</h1><p className="mt-2 text-sm text-brand-tint">Choose a communication-style target. This never measures identity, correctness, or employability.</p><div className="mt-5 rounded-2xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm">Prompts are synthetic fixtures. Your recording is not scored while speech inference is unavailable, and audio stays only in memory until it is discarded.</div>
 <fieldset className="mt-6"><legend className="font-semibold">1. Choose your target style</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{profiles.map(p=><button key={p.profileId} aria-pressed={profileId===p.profileId} onClick={()=>setProfileId(p.profileId)} className={`rounded-xl border p-3 text-left focus:ring-2 ${profileId===p.profileId?'border-brand-primary bg-brand-primary/20':'border-white/20'}`}><b>{p.displayName}</b><span className="block text-xs text-brand-tint">{p.description}</span></button>)}</div></fieldset>
 <fieldset className="mt-6"><legend className="font-semibold">2. Choose practice mode</legend><div className="mt-2 flex flex-wrap gap-2">{modes.map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)} className="rounded-full border border-white/20 px-4 py-2 focus:ring-2">{label}</button>)}</div></fieldset>
 {prompt&&<section className="mt-6 rounded-2xl bg-white/5 p-5"><h2 className="font-semibold">3. Read or respond</h2><p className="my-5 text-xl">{prompt.displayText}</p><p className="text-xs text-brand-tint">{prompt.referenceLabel}</p><p className="mt-2 text-xs">Recording stops automatically after {Math.ceil(prompt.maxDurationMs/1000)} seconds.</p>{['idle','canceled','result','permission_denied','permission_revoked','device_lost','offline','unsupported','error'].includes(recorder.state)&&<button onClick={()=>{practiceGeneration.current++;void recorder.startRecording({maxDurationMs:prompt.maxDurationMs,maxBytes:5*1024*1024}).catch(()=>undefined)}} className="mt-4 rounded-xl bg-brand-primary px-5 py-3 font-bold focus:ring-2">{['idle','canceled','result'].includes(recorder.state)?'I consent — start microphone':'Retry microphone'}</button>}{recorder.state==='recording'&&<button onClick={recorder.stopRecording} className="mt-4 rounded-xl bg-red-500 px-5 py-3 font-bold">Stop recording</button>}{recorder.audioBlob&&<div className="mt-4"><audio controls src={previewUrl} className="w-full" aria-label="Preview your recording"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void submit()} disabled={submitting} aria-busy={submitting} className="rounded-xl bg-brand-primary px-5 py-3 font-bold disabled:opacity-60">{submitting?'Checking availability…':'Check scoring availability'}</button><button onClick={()=>void cancelPractice()} className="rounded-xl border px-5 py-3">Discard and re-record</button>{attemptId.current&&error&&<button onClick={()=>void recoverSubmission()} className="rounded-xl border px-5 py-3">Check attempt status</button>}</div></div>}{recorder.errorMessage&&<p role="alert" className="mt-3 text-red-300">{recorder.errorMessage}</p>}</section>}{error&&<p role="alert" className="mt-4 text-red-300">{error}</p>}
 {score&&<section className="mt-6"><h2 className="text-2xl font-semibold">Scoring unavailable</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(score.dimensions).map(([name,d])=><article key={name} className="rounded-xl border border-white/10 p-4"><h3 className="capitalize">{name==='targetStyle'?'Selected target style':name}</h3><strong className="text-2xl">{['sufficient','limited'].includes(d.evidenceStatus)?d.score:'No score'}</strong><p className="text-xs">Evidence: {d.evidenceStatus} · confidence {Math.round(d.confidence*100)}%</p><p className="mt-2 text-sm">{d.summary}</p></article>)}</div><h3 className="mt-5 font-semibold">Next actions</h3><ol className="list-decimal pl-6">{score.coaching.map(c=><li key={c.rank}>{c.action}</li>)}</ol><p className="mt-4 text-xs text-brand-tint">{score.disclaimer}</p></section>}
 <section className="mt-8" aria-labelledby="accent-history-heading"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 id="accent-history-heading" className="text-2xl font-semibold">Attempt history</h2><p className="text-sm text-brand-tint">{history.length} saved derived {history.length===1?'attempt':'attempts'} · raw audio is never retained.</p></div><button onClick={()=>void loadHistory()} disabled={historyLoading} className="rounded-xl border px-4 py-2 disabled:opacity-60">{historyLoading?'Refreshing…':'Refresh'}</button></div>
 {historyError&&<p role="alert" className="mt-3 text-red-300">{historyError}</p>}
 {!historyLoading&&!history.length&&!historyError&&<p className="mt-3 rounded-xl border border-white/10 p-4">No saved attempts yet. Complete a recording to start your progression history.</p>}
 <div className="mt-4 grid gap-3 sm:grid-cols-2">{history.map(item=><article key={item.attempt_id} className="min-w-0 rounded-xl border border-white/10 p-4"><h3 className="font-semibold">{item.result.profileId.includes('GB')?'UK':'US'} · {new Date(item.created_at).toLocaleDateString()}</h3><p className="mt-1 text-xs">{item.result.evidenceProvenance==='user_recording_unscored'?'User recording · unscored':'Synthetic fixture score'} · {Math.ceil(item.duration_ms/1000)}s</p><p className="mt-2 text-sm">Evidence: {Object.values(item.evidenceStatus).every(status=>status==='unsupported')?'unsupported':'mixed'}</p><button onClick={()=>void deleteAttempt(item.attempt_id)} disabled={deletingId!==null} aria-label="Delete this accent practice attempt" className="mt-3 rounded-lg border border-red-300/40 px-3 py-2 text-sm disabled:opacity-60">{deletingId===item.attempt_id?'Deleting…':'Delete attempt'}</button></article>)}</div>
 </section></main>;
}
