import React, { useEffect, useMemo, useRef, useState } from 'react';
import { z } from 'zod';
import type { AccentProfileV1, AccentScoreV1, PracticePromptV1 } from 'mockmate-shared';
import { AccentProfileV1Schema, AccentScoreV1Schema, PracticePromptV1Schema } from 'mockmate-shared';
import { apiClient } from '../../services/apiClient';
import { useAudioRecorder } from './useAudioRecorder';

const Catalog = z.object({ contractVersion:z.literal('accent-profile-catalog.v1'), profiles:z.array(AccentProfileV1Schema), practiceModes:z.array(z.string()), fixture:z.literal(true), retention:z.literal('derived-results-only') });
const Prompt = z.object({ prompt:PracticePromptV1Schema, scoringPolicyVersion:z.string(), fixture:z.literal(true) });
const Result = z.object({ score:AccentScoreV1Schema, replayed:z.boolean(), adapter:z.literal('scoring-unavailable-v1'), retention:z.literal('derived-results-only') });
const modes = [['word','Word'],['phrase','Phrase'],['sentence_reading','Sentence'],['free_response','Free response']] as const;

export default function AccentPracticeV1({ onExit }:{ onExit:()=>void }) {
 const recorder=useAudioRecorder(); const [profiles,setProfiles]=useState<AccentProfileV1[]>([]); const [profileId,setProfileId]=useState('en-GB-general-v1'); const [mode,setMode]=useState<typeof modes[number][0]>('word'); const [prompt,setPrompt]=useState<PracticePromptV1|null>(null); const [policy,setPolicy]=useState(''); const [score,setScore]=useState<AccentScoreV1|null>(null); const [error,setError]=useState('');
 const previewUrl=useMemo(()=>recorder.audioBlob?URL.createObjectURL(recorder.audioBlob):'',[recorder.audioBlob]); useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl)},[previewUrl]);
 useEffect(()=>{apiClient.get('clearspeak/v1/accent/catalog',Catalog).then(x=>setProfiles(x.profiles)).catch(()=>setError('Accent practice is unavailable.'))},[]);
 const promptGeneration=useRef(0);
 useEffect(()=>{const generation=++promptGeneration.current;setScore(null);setPrompt(null);recorder.abortRecording();apiClient.post('clearspeak/v1/accent/prompts',Prompt,{profileId,profileVersion:1,mode}).then(x=>{if(generation!==promptGeneration.current)return;setPrompt(x.prompt);setPolicy(x.scoringPolicyVersion)}).catch(()=>{if(generation===promptGeneration.current)setError('Could not load this prompt.')});return()=>{promptGeneration.current++}},[profileId,mode]);
 const pendingSubmit=useRef<Promise<void>|null>(null); const attemptId=useRef<string|null>(null); const [submitting,setSubmitting]=useState(false);
 const submit=()=>{if(pendingSubmit.current)return pendingSubmit.current;const run=(async()=>{if(!navigator.onLine){setError('You are offline. No result was created.');return}if(!prompt||!recorder.audioBlob)return;attemptId.current??=crypto.randomUUID();setSubmitting(true);const form=new FormData();form.append('audio',recorder.audioBlob,'ephemeral-recording.webm');form.append('metadata',JSON.stringify({attemptId:attemptId.current,durationMs:recorder.durationMs,mode,profileId,profileVersion:prompt.profileVersion,promptId:prompt.promptId,promptVersion:prompt.promptVersion,promptContentHash:prompt.contentHash,referenceSetVersion:prompt.referenceSetVersion,scoringPolicyVersion:policy}));try{const x=await apiClient.post('clearspeak/v1/accent/attempts',Result,form);setScore(x.score);recorder.clearAudio()}catch{setError('Submission failed. Your audio was discarded; please record again.');recorder.clearAudio()}finally{setSubmitting(false);pendingSubmit.current=null;attemptId.current=null}})();pendingSubmit.current=run;return run};
 return <main className="mx-auto w-full max-w-3xl overflow-x-hidden p-4 text-white sm:p-8" aria-live="polite"><button onClick={()=>{recorder.abortRecording();onExit()}} className="mb-5 text-sm text-brand-tint focus:ring-2">← ClearSpeak home</button><h1 className="text-3xl font-semibold">Accent practice V1</h1><p className="mt-2 text-sm text-brand-tint">Choose a communication-style target. This never measures identity, correctness, or employability.</p><div className="mt-5 rounded-2xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm">Prompts are synthetic fixtures. Your recording is not scored while speech inference is unavailable, and audio stays only in memory until it is discarded.</div>
 <fieldset className="mt-6"><legend className="font-semibold">1. Choose your target style</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{profiles.map(p=><button key={p.profileId} aria-pressed={profileId===p.profileId} onClick={()=>setProfileId(p.profileId)} className={`rounded-xl border p-3 text-left focus:ring-2 ${profileId===p.profileId?'border-brand-primary bg-brand-primary/20':'border-white/20'}`}><b>{p.displayName}</b><span className="block text-xs text-brand-tint">{p.description}</span></button>)}</div></fieldset>
 <fieldset className="mt-6"><legend className="font-semibold">2. Choose practice mode</legend><div className="mt-2 flex flex-wrap gap-2">{modes.map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)} className="rounded-full border border-white/20 px-4 py-2 focus:ring-2">{label}</button>)}</div></fieldset>
 {prompt&&<section className="mt-6 rounded-2xl bg-white/5 p-5"><h2 className="font-semibold">3. Read or respond</h2><p className="my-5 text-xl">{prompt.displayText}</p><p className="text-xs text-brand-tint">{prompt.referenceLabel}</p>{['idle','canceled','result','permission_denied','permission_revoked','device_lost','offline','unsupported','error'].includes(recorder.state)&&<button onClick={()=>void recorder.startRecording().catch(()=>undefined)} className="mt-4 rounded-xl bg-brand-primary px-5 py-3 font-bold focus:ring-2">{['idle','canceled','result'].includes(recorder.state)?'I consent — start microphone':'Retry microphone'}</button>}{recorder.state==='recording'&&<button onClick={recorder.stopRecording} className="mt-4 rounded-xl bg-red-500 px-5 py-3 font-bold">Stop recording</button>}{recorder.audioBlob&&<div className="mt-4"><audio controls src={previewUrl} className="w-full" aria-label="Preview your recording"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void submit()} disabled={submitting} aria-busy={submitting} className="rounded-xl bg-brand-primary px-5 py-3 font-bold disabled:opacity-60">{submitting?'Checking availability…':'Check scoring availability'}</button><button onClick={recorder.abortRecording} className="rounded-xl border px-5 py-3">Discard and re-record</button></div></div>}{recorder.errorMessage&&<p role="alert" className="mt-3 text-red-300">{recorder.errorMessage}</p>}</section>}{error&&<p role="alert" className="mt-4 text-red-300">{error}</p>}
 {score&&<section className="mt-6"><h2 className="text-2xl font-semibold">Scoring unavailable</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(score.dimensions).map(([name,d])=><article key={name} className="rounded-xl border border-white/10 p-4"><h3 className="capitalize">{name==='targetStyle'?'Selected target style':name}</h3><strong className="text-2xl">{['sufficient','limited'].includes(d.evidenceStatus)?d.score:'No score'}</strong><p className="text-xs">Evidence: {d.evidenceStatus} · confidence {Math.round(d.confidence*100)}%</p><p className="mt-2 text-sm">{d.summary}</p></article>)}</div><h3 className="mt-5 font-semibold">Next actions</h3><ol className="list-decimal pl-6">{score.coaching.map(c=><li key={c.rank}>{c.action}</li>)}</ol><p className="mt-4 text-xs text-brand-tint">{score.disclaimer}</p></section>}</main>;
}
